apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: {{ .Release.Name }}-myapp
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.nginx.type }}
  selector:
    app: {{ .Release.Name }}-myapp
    release: {{ .Release.Name }}
  ports:
  - port: {{ .Values.service.nginx.port }}
    targetPort: {{ .Values.service.nginx.targetPort }}
    name: nginx-port
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-multitool
  labels:
    app: {{ .Release.Name }}-myapp
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.multitool.type }}
  selector:
    app: {{ .Release.Name }}-myapp
    release: {{ .Release.Name }}
  ports:
  - port: {{ .Values.service.multitool.port }}
    targetPort: {{ .Values.service.multitool.targetPort }}
    name: multitool-port
